import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-fema-public-assistance-reimbursement",
  "engine": "recovery",
  "title": "FEMA Public Assistance Reimbursement",
  "shortTitle": "FEMA Public Assistance Reimbursement",
  "tagline": "Quantify, recover, and prevent financial leakage through fema public assistance reimbursement",
  "industry": "Disaster Grant Recovery",
  "uiPort": 4637,
  "apiPort": 5637,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "FEMA Public Assistance Reimbursement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "FEMA Reimbursement",
    "expectedLabel": "Eligible Public Assistance",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "FEMA Public Assistance Reimbursement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("disaster-declaration-registry","FPA01","Disaster declaration registry","Execute disaster declaration registry using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed disaster declaration registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Disaster declaration registry Reference","text","FPA01-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("applicant-eligibility","FPA02","Applicant eligibility","Execute applicant eligibility using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed applicant eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Applicant eligibility Reference","text","FPA02-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("site-damage-inventory","FPA03","Site damage inventory","Execute site damage inventory using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed site damage inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Site damage inventory Reference","text","FPA03-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("emergency-work-classification","FPA04","Emergency work classification","Execute emergency work classification using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed emergency work classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Emergency work classification Reference","text","FPA04-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("permanent-work-classification","FPA05","Permanent work classification","Execute permanent work classification using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed permanent work classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Permanent work classification Reference","text","FPA05-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("force-account-labor-calculation","FPA06","Force-account labor calculation","Execute force-account labor calculation using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed force-account labor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Force-account labor calculation Reference","text","FPA06-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("equipment-rate-calculation","FPA07","Equipment rate calculation","Execute equipment rate calculation using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed equipment rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Equipment rate calculation Reference","text","FPA07-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("procurement-evidence","FPA08","Procurement evidence","Execute procurement evidence using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed procurement evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Procurement evidence Reference","text","FPA08-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("insurance-reduction-coordination","FPA09","Insurance reduction coordination","Execute insurance reduction coordination using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed insurance reduction coordination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Insurance reduction coordination Reference","text","FPA09-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("cost-reasonableness-validation","FPA10","Cost reasonableness validation","Execute cost reasonableness validation using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed cost reasonableness validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Cost reasonableness validation Reference","text","FPA10-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("project-worksheet-preparation","FPA11","Project worksheet preparation","Execute project worksheet preparation using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed project worksheet preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Project worksheet preparation Reference","text","FPA11-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("environmental-historic-preservation","FPA12","Environmental historic preservation","Execute environmental historic preservation using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed environmental historic preservation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Environmental historic preservation Reference","text","FPA12-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("documentation-request-workflow","FPA13","Documentation request workflow","Execute documentation request workflow using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed documentation request workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Documentation request workflow Reference","text","FPA13-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("obligation-draw-tracking","FPA14","Obligation draw tracking","Execute obligation draw tracking using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed obligation draw tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Obligation draw tracking Reference","text","FPA14-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]}),
feature("closeout-audit-package","FPA15","Closeout audit package","Execute closeout audit package using disaster declarations, applicants, damaged sites, emergency and permanent work, force-account labor, equipment, contracts, insurance, cost reasonableness, project worksheets, environmental evidence, obligations, draws, and closeout.","Produce a governed closeout audit package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Applicant / Declared Disaster","text","Applicant / Declared Disaster · Standard Case"],["caseReference","Closeout audit package Reference","text","FPA15-2026-001"],["reimbursedAmount","FEMA Reimbursement","currency",1271000],["eligibleAmount","Eligible Public Assistance","currency",1499780],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Disaster declaration registry case","Applicant eligibility case","Site damage inventory case","Emergency work classification case","Permanent work classification case"]})
]);
